data <- read.table(file="household_power_consumption.txt",header = TRUE,sep=";",na.strings = c("?"))
data$Date <- as.Date(as.character(data$Date),"%d/%m/%Y")
sub_data <- subset(data, (Date >= as.Date("2007-02-01")&(Date <= as.Date("2007-02-02")) ))
dim(sub_data)
png("plot2.png")
plot(strptime(paste(sub_data$Date,sub_data$Time, sep=" "), "%Y-%m-%d %H:%M:%S"), sub_data$Global_active_power,type="l", ylab="Global Active Power (kilowatts)",xlab="") 
dev.off()