data <- read.table(file="household_power_consumption.txt",header = TRUE,sep=";",na.strings = c("?"))
data$Date <- as.Date(as.character(data$Date),"%d/%m/%Y")
sub_data <- subset(data, (Date >= as.Date("2007-02-01")&(Date <= as.Date("2007-02-02")) ))
dim(sub_data)
png("plot1.png")
hist(as.numeric(sub_data$Global_active_power),col="red",xlab = "Global Active Power (kilowatts)",main = "Global Active Power")
dev.off()